# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    BoolTagId
    ITagId
    UTagId
    FTagId
    PtrTagId
    AptrTagId
    ArrayTagId
    TypeTagId
    ObjectTagId
    FldTagId
    ProcTagId
    ParamsTagId
    ParamTagId
    RetsTagId
    ClobberTagId
    BodyTagId
    VarTagId
    STagId
    SsizeTagId
    MovTagId
    LeaTagId
    MovapdTagId
    MovsdTagId
    AddTagId
    SubTagId
    MulTagId
    ImulTagId
    DivTagId
    IdivTagId
    AddsdTagId
    SubsdTagId
    MulsdTagId
    DivsdTagId
    AndTagId
    OrTagId
    XorTagId
    ShlTagId
    ShrTagId
    SalTagId
    SarTagId
    IncTagId
    DecTagId
    NegTagId
    NotTagId
    CmpTagId
    TestTagId
    SeteTagId
    SetzTagId
    SetneTagId
    SetnzTagId
    SetaTagId
    SetnbeTagId
    SetaeTagId
    SetnbTagId
    SetncTagId
    SetbTagId
    SetnaeTagId
    SetcTagId
    SetbeTagId
    SetnaTagId
    SetgTagId
    SetnleTagId
    SetgeTagId
    SetnlTagId
    SetlTagId
    SetngeTagId
    SetleTagId
    SetngTagId
    SetoTagId
    SetsTagId
    SetpTagId
    JmpTagId
    JeTagId
    JzTagId
    JneTagId
    JnzTagId
    JgTagId
    JngTagId
    JgeTagId
    JngeTagId
    JaTagId
    JnaTagId
    JaeTagId
    JnaeTagId
    CallTagId
    RetTagId
    PushTagId
    PopTagId
    NopTagId
    SyscallTagId
    LabTagId
    IteTagId
    LoopTagId
    StmtsTagId
    DotTagId
    AtTagId
    MemTagId
    RodataTagId
    CastTagId
    RaxTagId
    RbxTagId
    RcxTagId
    RdxTagId
    RsiTagId
    RdiTagId
    RbpTagId
    RspTagId
    R8TagId
    R9TagId
    R10TagId
    R11TagId
    R12TagId
    R13TagId
    R14TagId
    R15TagId
    R0TagId
    R1TagId
    R2TagId
    R3TagId
    R4TagId
    R5TagId
    R6TagId
    R7TagId
    Xmm0TagId
    Xmm1TagId
    Xmm2TagId
    Xmm3TagId
    Xmm4TagId
    Xmm5TagId
    Xmm6TagId
    Xmm7TagId
    Xmm8TagId
    Xmm9TagId
    Xmm10TagId
    Xmm11TagId
    Xmm12TagId
    Xmm13TagId
    Xmm14TagId
    Xmm15TagId
    OfTagId
    NoTagId
    ZfTagId
    NzTagId
    SfTagId
    NsTagId
    CfTagId
    NcTagId
    PfTagId
    NpTagId
const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("bool", 1),
    ("i", 2),
    ("u", 3),
    ("f", 4),
    ("ptr", 5),
    ("aptr", 6),
    ("array", 7),
    ("type", 8),
    ("object", 9),
    ("fld", 10),
    ("proc", 11),
    ("params", 12),
    ("param", 13),
    ("rets", 14),
    ("clobber", 15),
    ("body", 16),
    ("var", 17),
    ("s", 18),
    ("ssize", 19),
    ("mov", 20),
    ("lea", 21),
    ("movapd", 22),
    ("movsd", 23),
    ("add", 24),
    ("sub", 25),
    ("mul", 26),
    ("imul", 27),
    ("div", 28),
    ("idiv", 29),
    ("addsd", 30),
    ("subsd", 31),
    ("mulsd", 32),
    ("divsd", 33),
    ("and", 34),
    ("or", 35),
    ("xor", 36),
    ("shl", 37),
    ("shr", 38),
    ("sal", 39),
    ("sar", 40),
    ("inc", 41),
    ("dec", 42),
    ("neg", 43),
    ("not", 44),
    ("cmp", 45),
    ("test", 46),
    ("sete", 47),
    ("setz", 48),
    ("setne", 49),
    ("setnz", 50),
    ("seta", 51),
    ("setnbe", 52),
    ("setae", 53),
    ("setnb", 54),
    ("setnc", 55),
    ("setb", 56),
    ("setnae", 57),
    ("setc", 58),
    ("setbe", 59),
    ("setna", 60),
    ("setg", 61),
    ("setnle", 62),
    ("setge", 63),
    ("setnl", 64),
    ("setl", 65),
    ("setnge", 66),
    ("setle", 67),
    ("setng", 68),
    ("seto", 69),
    ("sets", 70),
    ("setp", 71),
    ("jmp", 72),
    ("je", 73),
    ("jz", 74),
    ("jne", 75),
    ("jnz", 76),
    ("jg", 77),
    ("jng", 78),
    ("jge", 79),
    ("jnge", 80),
    ("ja", 81),
    ("jna", 82),
    ("jae", 83),
    ("jnae", 84),
    ("call", 85),
    ("ret", 86),
    ("push", 87),
    ("pop", 88),
    ("nop", 89),
    ("syscall", 90),
    ("lab", 91),
    ("ite", 92),
    ("loop", 93),
    ("stmts", 94),
    ("dot", 95),
    ("at", 96),
    ("mem", 97),
    ("rodata", 98),
    ("cast", 100),
    ("rax", 101),
    ("rbx", 102),
    ("rcx", 103),
    ("rdx", 104),
    ("rsi", 105),
    ("rdi", 106),
    ("rbp", 107),
    ("rsp", 108),
    ("r8", 109),
    ("r9", 110),
    ("r10", 111),
    ("r11", 112),
    ("r12", 113),
    ("r13", 114),
    ("r14", 115),
    ("r15", 116),
    ("r0", 117),
    ("r1", 118),
    ("r2", 119),
    ("r3", 120),
    ("r4", 121),
    ("r5", 122),
    ("r6", 123),
    ("r7", 124),
    ("xmm0", 125),
    ("xmm1", 126),
    ("xmm2", 127),
    ("xmm3", 128),
    ("xmm4", 129),
    ("xmm5", 130),
    ("xmm6", 131),
    ("xmm7", 132),
    ("xmm8", 133),
    ("xmm9", 134),
    ("xmm10", 135),
    ("xmm11", 136),
    ("xmm12", 137),
    ("xmm13", 138),
    ("xmm14", 139),
    ("xmm15", 140),
    ("of", 141),
    ("no", 142),
    ("zf", 143),
    ("nz", 144),
    ("sf", 145),
    ("ns", 146),
    ("cf", 147),
    ("nc", 148),
    ("pf", 149),
    ("np", 150)
  ]
